"use client";
import { Montserrat } from "@next/font/google";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import { QueryClient, QueryClientProvider } from "react-query";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const queryClient = new QueryClient();
const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>E Store</title>
        <meta property="og:title" content="estore.com" key="title" />
      </Head>
      <QueryClientProvider client={queryClient} contextSharing={true}>
        <ToastContainer newestOnTop={true} autoClose={500} />
        <body
          className="w-full font-montserrat bg-sky-50 mx-auto h-[100vh]"
          suppressHydrationWarning={true}
        >
          {children}
        </body>
      </QueryClientProvider>
    </html>
  );
}
